# Generated by Django 3.2.18 on 2023-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_toddolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toddolist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
